name: Deploy Firebase Functions

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: TechArtists/backend-firebase-function-save-payload/.github/workflows/firebaseFunctionDeploy.yml@main
    with:
      function-name: savePayload
      projects: "fitnessai-api,allstays-appex,dietbet-staging,stepbet-staging-99260,dietbet-5771b,stepbet-1210"
      target-bucket: appex_app_payloads
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
